[build]
  publish = "/"
  functions = "netlify/functions"
  command = ""  # Add empty command to prevent build errors

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"  # Optional but recommended
  external_node_modules = []
  included_files = ["netlify/functions/**"]  # Ensure all function files are included

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
