[build]
  publish = "/"
  functions = "netlify/functions"
  command = "npm install"  # Add this line to install dependencies

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]  # Mark as external

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
